update

diff --git a/.github/workflows/scan.yaml b/.github/workflows/scan.yaml
--- a/.github/workflows/scan.yaml
+++ b/.github/workflows/scan.yaml
@@ -20,9 +20,15 @@ jobs:
         id: get-org
         run: |
           ORG=$(curl -s -H "Authorization: Bearer ${{ secrets.Token_WF }}" \
-                 https://api.github.com/user | jq -r '.organization.login')
+                 https://api.github.com/user | jq -r '.organization.login // empty')
+          if [ -z "$ORG" ]; then
+            echo "Failed to retrieve organization information from GitHub API."
+            exit 1
+          fi
+
           NORMALIZED_ORG=$(echo $ORG | tr '[:upper:]' '[:lower:]' | tr '-' '_')
-          echo "ORG: $NORMALIZED_ORG"
+          echo "ORG: $NORMALIZED_ORG"  # Imprimir el valor de ORG
+
           echo "::set-output name=ORG::$NORMALIZED_ORG"
 
   Deploy:
